[package]
name = "io-uring-semantics"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9"
io-uring = { version = "0.6" }
tempfile = "3"
tokio = { version = "1", features = ["macros", "net", "process", "rt", "rt-multi-thread", "sync", "time"] }
uapi = { version = "0.2.13" }
